/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentRouteImport } from './routes/student'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EditProfileRouteImport } from './routes/edit-profile'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentTreeholeRouteImport } from './routes/student.treehole'
import { Route as StudentTextbookRouteImport } from './routes/student.textbook'
import { Route as StudentTestRouteImport } from './routes/student.test'
import { Route as StudentSettingsRouteImport } from './routes/student.settings'
import { Route as StudentProgressRouteImport } from './routes/student.progress'
import { Route as StudentMeRouteImport } from './routes/student.me'
import { Route as StudentLearnRouteImport } from './routes/student.learn'
import { Route as StudentKnowledgePointRouteImport } from './routes/student.knowledge-point'
import { Route as StudentAiRouteImport } from './routes/student.ai'
import { Route as ParentWellbeingRouteImport } from './routes/parent.wellbeing'
import { Route as ParentSubjectsRouteImport } from './routes/parent.subjects'
import { Route as ParentSettingsRouteImport } from './routes/parent.settings'
import { Route as ParentOverviewRouteImport } from './routes/parent.overview'
import { Route as ParentMeRouteImport } from './routes/parent.me'
import { Route as ParentChildrenRouteImport } from './routes/parent.children'
import { Route as StudentTestIndexRouteImport } from './routes/student.test.index'
import { Route as StudentProgressIndexRouteImport } from './routes/student.progress.index'
import { Route as StudentLearnIndexRouteImport } from './routes/student.learn.index'
import { Route as StudentTestWrongRouteImport } from './routes/student.test.wrong'
import { Route as StudentTestScoreRouteImport } from './routes/student.test.score'
import { Route as StudentTestResultRouteImport } from './routes/student.test.result'
import { Route as StudentTestQuizRouteImport } from './routes/student.test.quiz'
import { Route as StudentProgressSubjectRouteImport } from './routes/student.progress.$subject'
import { Route as StudentLearnSubjectRouteImport } from './routes/student.learn.$subject'
import { Route as StudentLearnSubjectChapterRouteImport } from './routes/student.learn.$subject.$chapter'

const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EditProfileRoute = EditProfileRouteImport.update({
  id: '/edit-profile',
  path: '/edit-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentTreeholeRoute = StudentTreeholeRouteImport.update({
  id: '/treehole',
  path: '/treehole',
  getParentRoute: () => StudentRoute,
} as any)
const StudentTextbookRoute = StudentTextbookRouteImport.update({
  id: '/textbook',
  path: '/textbook',
  getParentRoute: () => StudentRoute,
} as any)
const StudentTestRoute = StudentTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => StudentRoute,
} as any)
const StudentSettingsRoute = StudentSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProgressRoute = StudentProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => StudentRoute,
} as any)
const StudentMeRoute = StudentMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => StudentRoute,
} as any)
const StudentLearnRoute = StudentLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => StudentRoute,
} as any)
const StudentKnowledgePointRoute = StudentKnowledgePointRouteImport.update({
  id: '/knowledge-point',
  path: '/knowledge-point',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAiRoute = StudentAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => StudentRoute,
} as any)
const ParentWellbeingRoute = ParentWellbeingRouteImport.update({
  id: '/wellbeing',
  path: '/wellbeing',
  getParentRoute: () => ParentRoute,
} as any)
const ParentSubjectsRoute = ParentSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => ParentRoute,
} as any)
const ParentSettingsRoute = ParentSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ParentRoute,
} as any)
const ParentOverviewRoute = ParentOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => ParentRoute,
} as any)
const ParentMeRoute = ParentMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => ParentRoute,
} as any)
const ParentChildrenRoute = ParentChildrenRouteImport.update({
  id: '/children',
  path: '/children',
  getParentRoute: () => ParentRoute,
} as any)
const StudentTestIndexRoute = StudentTestIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentTestRoute,
} as any)
const StudentProgressIndexRoute = StudentProgressIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentProgressRoute,
} as any)
const StudentLearnIndexRoute = StudentLearnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentLearnRoute,
} as any)
const StudentTestWrongRoute = StudentTestWrongRouteImport.update({
  id: '/wrong',
  path: '/wrong',
  getParentRoute: () => StudentTestRoute,
} as any)
const StudentTestScoreRoute = StudentTestScoreRouteImport.update({
  id: '/score',
  path: '/score',
  getParentRoute: () => StudentTestRoute,
} as any)
const StudentTestResultRoute = StudentTestResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => StudentTestRoute,
} as any)
const StudentTestQuizRoute = StudentTestQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => StudentTestRoute,
} as any)
const StudentProgressSubjectRoute = StudentProgressSubjectRouteImport.update({
  id: '/$subject',
  path: '/$subject',
  getParentRoute: () => StudentProgressRoute,
} as any)
const StudentLearnSubjectRoute = StudentLearnSubjectRouteImport.update({
  id: '/$subject',
  path: '/$subject',
  getParentRoute: () => StudentLearnRoute,
} as any)
const StudentLearnSubjectChapterRoute =
  StudentLearnSubjectChapterRouteImport.update({
    id: '/$chapter',
    path: '/$chapter',
    getParentRoute: () => StudentLearnSubjectRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/edit-profile': typeof EditProfileRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/parent': typeof ParentRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/parent/children': typeof ParentChildrenRoute
  '/parent/me': typeof ParentMeRoute
  '/parent/overview': typeof ParentOverviewRoute
  '/parent/settings': typeof ParentSettingsRoute
  '/parent/subjects': typeof ParentSubjectsRoute
  '/parent/wellbeing': typeof ParentWellbeingRoute
  '/student/ai': typeof StudentAiRoute
  '/student/knowledge-point': typeof StudentKnowledgePointRoute
  '/student/learn': typeof StudentLearnRouteWithChildren
  '/student/me': typeof StudentMeRoute
  '/student/progress': typeof StudentProgressRouteWithChildren
  '/student/settings': typeof StudentSettingsRoute
  '/student/test': typeof StudentTestRouteWithChildren
  '/student/textbook': typeof StudentTextbookRoute
  '/student/treehole': typeof StudentTreeholeRoute
  '/student/learn/$subject': typeof StudentLearnSubjectRouteWithChildren
  '/student/progress/$subject': typeof StudentProgressSubjectRoute
  '/student/test/quiz': typeof StudentTestQuizRoute
  '/student/test/result': typeof StudentTestResultRoute
  '/student/test/score': typeof StudentTestScoreRoute
  '/student/test/wrong': typeof StudentTestWrongRoute
  '/student/learn/': typeof StudentLearnIndexRoute
  '/student/progress/': typeof StudentProgressIndexRoute
  '/student/test/': typeof StudentTestIndexRoute
  '/student/learn/$subject/$chapter': typeof StudentLearnSubjectChapterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/edit-profile': typeof EditProfileRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/parent': typeof ParentRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/parent/children': typeof ParentChildrenRoute
  '/parent/me': typeof ParentMeRoute
  '/parent/overview': typeof ParentOverviewRoute
  '/parent/settings': typeof ParentSettingsRoute
  '/parent/subjects': typeof ParentSubjectsRoute
  '/parent/wellbeing': typeof ParentWellbeingRoute
  '/student/ai': typeof StudentAiRoute
  '/student/knowledge-point': typeof StudentKnowledgePointRoute
  '/student/me': typeof StudentMeRoute
  '/student/settings': typeof StudentSettingsRoute
  '/student/textbook': typeof StudentTextbookRoute
  '/student/treehole': typeof StudentTreeholeRoute
  '/student/learn/$subject': typeof StudentLearnSubjectRouteWithChildren
  '/student/progress/$subject': typeof StudentProgressSubjectRoute
  '/student/test/quiz': typeof StudentTestQuizRoute
  '/student/test/result': typeof StudentTestResultRoute
  '/student/test/score': typeof StudentTestScoreRoute
  '/student/test/wrong': typeof StudentTestWrongRoute
  '/student/learn': typeof StudentLearnIndexRoute
  '/student/progress': typeof StudentProgressIndexRoute
  '/student/test': typeof StudentTestIndexRoute
  '/student/learn/$subject/$chapter': typeof StudentLearnSubjectChapterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/edit-profile': typeof EditProfileRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/parent': typeof ParentRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/parent/children': typeof ParentChildrenRoute
  '/parent/me': typeof ParentMeRoute
  '/parent/overview': typeof ParentOverviewRoute
  '/parent/settings': typeof ParentSettingsRoute
  '/parent/subjects': typeof ParentSubjectsRoute
  '/parent/wellbeing': typeof ParentWellbeingRoute
  '/student/ai': typeof StudentAiRoute
  '/student/knowledge-point': typeof StudentKnowledgePointRoute
  '/student/learn': typeof StudentLearnRouteWithChildren
  '/student/me': typeof StudentMeRoute
  '/student/progress': typeof StudentProgressRouteWithChildren
  '/student/settings': typeof StudentSettingsRoute
  '/student/test': typeof StudentTestRouteWithChildren
  '/student/textbook': typeof StudentTextbookRoute
  '/student/treehole': typeof StudentTreeholeRoute
  '/student/learn/$subject': typeof StudentLearnSubjectRouteWithChildren
  '/student/progress/$subject': typeof StudentProgressSubjectRoute
  '/student/test/quiz': typeof StudentTestQuizRoute
  '/student/test/result': typeof StudentTestResultRoute
  '/student/test/score': typeof StudentTestScoreRoute
  '/student/test/wrong': typeof StudentTestWrongRoute
  '/student/learn/': typeof StudentLearnIndexRoute
  '/student/progress/': typeof StudentProgressIndexRoute
  '/student/test/': typeof StudentTestIndexRoute
  '/student/learn/$subject/$chapter': typeof StudentLearnSubjectChapterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/edit-profile'
    | '/login'
    | '/onboarding'
    | '/parent'
    | '/student'
    | '/parent/children'
    | '/parent/me'
    | '/parent/overview'
    | '/parent/settings'
    | '/parent/subjects'
    | '/parent/wellbeing'
    | '/student/ai'
    | '/student/knowledge-point'
    | '/student/learn'
    | '/student/me'
    | '/student/progress'
    | '/student/settings'
    | '/student/test'
    | '/student/textbook'
    | '/student/treehole'
    | '/student/learn/$subject'
    | '/student/progress/$subject'
    | '/student/test/quiz'
    | '/student/test/result'
    | '/student/test/score'
    | '/student/test/wrong'
    | '/student/learn/'
    | '/student/progress/'
    | '/student/test/'
    | '/student/learn/$subject/$chapter'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/edit-profile'
    | '/login'
    | '/onboarding'
    | '/parent'
    | '/student'
    | '/parent/children'
    | '/parent/me'
    | '/parent/overview'
    | '/parent/settings'
    | '/parent/subjects'
    | '/parent/wellbeing'
    | '/student/ai'
    | '/student/knowledge-point'
    | '/student/me'
    | '/student/settings'
    | '/student/textbook'
    | '/student/treehole'
    | '/student/learn/$subject'
    | '/student/progress/$subject'
    | '/student/test/quiz'
    | '/student/test/result'
    | '/student/test/score'
    | '/student/test/wrong'
    | '/student/learn'
    | '/student/progress'
    | '/student/test'
    | '/student/learn/$subject/$chapter'
  id:
    | '__root__'
    | '/'
    | '/edit-profile'
    | '/login'
    | '/onboarding'
    | '/parent'
    | '/student'
    | '/parent/children'
    | '/parent/me'
    | '/parent/overview'
    | '/parent/settings'
    | '/parent/subjects'
    | '/parent/wellbeing'
    | '/student/ai'
    | '/student/knowledge-point'
    | '/student/learn'
    | '/student/me'
    | '/student/progress'
    | '/student/settings'
    | '/student/test'
    | '/student/textbook'
    | '/student/treehole'
    | '/student/learn/$subject'
    | '/student/progress/$subject'
    | '/student/test/quiz'
    | '/student/test/result'
    | '/student/test/score'
    | '/student/test/wrong'
    | '/student/learn/'
    | '/student/progress/'
    | '/student/test/'
    | '/student/learn/$subject/$chapter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EditProfileRoute: typeof EditProfileRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ParentRoute: typeof ParentRouteWithChildren
  StudentRoute: typeof StudentRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-profile': {
      id: '/edit-profile'
      path: '/edit-profile'
      fullPath: '/edit-profile'
      preLoaderRoute: typeof EditProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/treehole': {
      id: '/student/treehole'
      path: '/treehole'
      fullPath: '/student/treehole'
      preLoaderRoute: typeof StudentTreeholeRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/textbook': {
      id: '/student/textbook'
      path: '/textbook'
      fullPath: '/student/textbook'
      preLoaderRoute: typeof StudentTextbookRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/test': {
      id: '/student/test'
      path: '/test'
      fullPath: '/student/test'
      preLoaderRoute: typeof StudentTestRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/settings': {
      id: '/student/settings'
      path: '/settings'
      fullPath: '/student/settings'
      preLoaderRoute: typeof StudentSettingsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/progress': {
      id: '/student/progress'
      path: '/progress'
      fullPath: '/student/progress'
      preLoaderRoute: typeof StudentProgressRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/me': {
      id: '/student/me'
      path: '/me'
      fullPath: '/student/me'
      preLoaderRoute: typeof StudentMeRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/learn': {
      id: '/student/learn'
      path: '/learn'
      fullPath: '/student/learn'
      preLoaderRoute: typeof StudentLearnRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/knowledge-point': {
      id: '/student/knowledge-point'
      path: '/knowledge-point'
      fullPath: '/student/knowledge-point'
      preLoaderRoute: typeof StudentKnowledgePointRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/ai': {
      id: '/student/ai'
      path: '/ai'
      fullPath: '/student/ai'
      preLoaderRoute: typeof StudentAiRouteImport
      parentRoute: typeof StudentRoute
    }
    '/parent/wellbeing': {
      id: '/parent/wellbeing'
      path: '/wellbeing'
      fullPath: '/parent/wellbeing'
      preLoaderRoute: typeof ParentWellbeingRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/subjects': {
      id: '/parent/subjects'
      path: '/subjects'
      fullPath: '/parent/subjects'
      preLoaderRoute: typeof ParentSubjectsRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/settings': {
      id: '/parent/settings'
      path: '/settings'
      fullPath: '/parent/settings'
      preLoaderRoute: typeof ParentSettingsRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/overview': {
      id: '/parent/overview'
      path: '/overview'
      fullPath: '/parent/overview'
      preLoaderRoute: typeof ParentOverviewRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/me': {
      id: '/parent/me'
      path: '/me'
      fullPath: '/parent/me'
      preLoaderRoute: typeof ParentMeRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/children': {
      id: '/parent/children'
      path: '/children'
      fullPath: '/parent/children'
      preLoaderRoute: typeof ParentChildrenRouteImport
      parentRoute: typeof ParentRoute
    }
    '/student/test/': {
      id: '/student/test/'
      path: '/'
      fullPath: '/student/test/'
      preLoaderRoute: typeof StudentTestIndexRouteImport
      parentRoute: typeof StudentTestRoute
    }
    '/student/progress/': {
      id: '/student/progress/'
      path: '/'
      fullPath: '/student/progress/'
      preLoaderRoute: typeof StudentProgressIndexRouteImport
      parentRoute: typeof StudentProgressRoute
    }
    '/student/learn/': {
      id: '/student/learn/'
      path: '/'
      fullPath: '/student/learn/'
      preLoaderRoute: typeof StudentLearnIndexRouteImport
      parentRoute: typeof StudentLearnRoute
    }
    '/student/test/wrong': {
      id: '/student/test/wrong'
      path: '/wrong'
      fullPath: '/student/test/wrong'
      preLoaderRoute: typeof StudentTestWrongRouteImport
      parentRoute: typeof StudentTestRoute
    }
    '/student/test/score': {
      id: '/student/test/score'
      path: '/score'
      fullPath: '/student/test/score'
      preLoaderRoute: typeof StudentTestScoreRouteImport
      parentRoute: typeof StudentTestRoute
    }
    '/student/test/result': {
      id: '/student/test/result'
      path: '/result'
      fullPath: '/student/test/result'
      preLoaderRoute: typeof StudentTestResultRouteImport
      parentRoute: typeof StudentTestRoute
    }
    '/student/test/quiz': {
      id: '/student/test/quiz'
      path: '/quiz'
      fullPath: '/student/test/quiz'
      preLoaderRoute: typeof StudentTestQuizRouteImport
      parentRoute: typeof StudentTestRoute
    }
    '/student/progress/$subject': {
      id: '/student/progress/$subject'
      path: '/$subject'
      fullPath: '/student/progress/$subject'
      preLoaderRoute: typeof StudentProgressSubjectRouteImport
      parentRoute: typeof StudentProgressRoute
    }
    '/student/learn/$subject': {
      id: '/student/learn/$subject'
      path: '/$subject'
      fullPath: '/student/learn/$subject'
      preLoaderRoute: typeof StudentLearnSubjectRouteImport
      parentRoute: typeof StudentLearnRoute
    }
    '/student/learn/$subject/$chapter': {
      id: '/student/learn/$subject/$chapter'
      path: '/$chapter'
      fullPath: '/student/learn/$subject/$chapter'
      preLoaderRoute: typeof StudentLearnSubjectChapterRouteImport
      parentRoute: typeof StudentLearnSubjectRoute
    }
  }
}

interface ParentRouteChildren {
  ParentChildrenRoute: typeof ParentChildrenRoute
  ParentMeRoute: typeof ParentMeRoute
  ParentOverviewRoute: typeof ParentOverviewRoute
  ParentSettingsRoute: typeof ParentSettingsRoute
  ParentSubjectsRoute: typeof ParentSubjectsRoute
  ParentWellbeingRoute: typeof ParentWellbeingRoute
}

const ParentRouteChildren: ParentRouteChildren = {
  ParentChildrenRoute: ParentChildrenRoute,
  ParentMeRoute: ParentMeRoute,
  ParentOverviewRoute: ParentOverviewRoute,
  ParentSettingsRoute: ParentSettingsRoute,
  ParentSubjectsRoute: ParentSubjectsRoute,
  ParentWellbeingRoute: ParentWellbeingRoute,
}

const ParentRouteWithChildren =
  ParentRoute._addFileChildren(ParentRouteChildren)

interface StudentLearnSubjectRouteChildren {
  StudentLearnSubjectChapterRoute: typeof StudentLearnSubjectChapterRoute
}

const StudentLearnSubjectRouteChildren: StudentLearnSubjectRouteChildren = {
  StudentLearnSubjectChapterRoute: StudentLearnSubjectChapterRoute,
}

const StudentLearnSubjectRouteWithChildren =
  StudentLearnSubjectRoute._addFileChildren(StudentLearnSubjectRouteChildren)

interface StudentLearnRouteChildren {
  StudentLearnSubjectRoute: typeof StudentLearnSubjectRouteWithChildren
  StudentLearnIndexRoute: typeof StudentLearnIndexRoute
}

const StudentLearnRouteChildren: StudentLearnRouteChildren = {
  StudentLearnSubjectRoute: StudentLearnSubjectRouteWithChildren,
  StudentLearnIndexRoute: StudentLearnIndexRoute,
}

const StudentLearnRouteWithChildren = StudentLearnRoute._addFileChildren(
  StudentLearnRouteChildren,
)

interface StudentProgressRouteChildren {
  StudentProgressSubjectRoute: typeof StudentProgressSubjectRoute
  StudentProgressIndexRoute: typeof StudentProgressIndexRoute
}

const StudentProgressRouteChildren: StudentProgressRouteChildren = {
  StudentProgressSubjectRoute: StudentProgressSubjectRoute,
  StudentProgressIndexRoute: StudentProgressIndexRoute,
}

const StudentProgressRouteWithChildren = StudentProgressRoute._addFileChildren(
  StudentProgressRouteChildren,
)

interface StudentTestRouteChildren {
  StudentTestQuizRoute: typeof StudentTestQuizRoute
  StudentTestResultRoute: typeof StudentTestResultRoute
  StudentTestScoreRoute: typeof StudentTestScoreRoute
  StudentTestWrongRoute: typeof StudentTestWrongRoute
  StudentTestIndexRoute: typeof StudentTestIndexRoute
}

const StudentTestRouteChildren: StudentTestRouteChildren = {
  StudentTestQuizRoute: StudentTestQuizRoute,
  StudentTestResultRoute: StudentTestResultRoute,
  StudentTestScoreRoute: StudentTestScoreRoute,
  StudentTestWrongRoute: StudentTestWrongRoute,
  StudentTestIndexRoute: StudentTestIndexRoute,
}

const StudentTestRouteWithChildren = StudentTestRoute._addFileChildren(
  StudentTestRouteChildren,
)

interface StudentRouteChildren {
  StudentAiRoute: typeof StudentAiRoute
  StudentKnowledgePointRoute: typeof StudentKnowledgePointRoute
  StudentLearnRoute: typeof StudentLearnRouteWithChildren
  StudentMeRoute: typeof StudentMeRoute
  StudentProgressRoute: typeof StudentProgressRouteWithChildren
  StudentSettingsRoute: typeof StudentSettingsRoute
  StudentTestRoute: typeof StudentTestRouteWithChildren
  StudentTextbookRoute: typeof StudentTextbookRoute
  StudentTreeholeRoute: typeof StudentTreeholeRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentAiRoute: StudentAiRoute,
  StudentKnowledgePointRoute: StudentKnowledgePointRoute,
  StudentLearnRoute: StudentLearnRouteWithChildren,
  StudentMeRoute: StudentMeRoute,
  StudentProgressRoute: StudentProgressRouteWithChildren,
  StudentSettingsRoute: StudentSettingsRoute,
  StudentTestRoute: StudentTestRouteWithChildren,
  StudentTextbookRoute: StudentTextbookRoute,
  StudentTreeholeRoute: StudentTreeholeRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditProfileRoute: EditProfileRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ParentRoute: ParentRouteWithChildren,
  StudentRoute: StudentRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
